import React, { useState } from 'react';
import { Card } from '../../components';
import { FiPieChart, FiTrendingUp, FiCalendar, FiClock } from 'react-icons/fi';

const Reports = () => {
  const [activeReport, setActiveReport] = useState('finance');

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white">System Reports & Analysis</h2>
        <p className="text-slate-500 dark:text-slate-400 text-sm">Review logs, sheets and metrics generated by the HRM portal</p>
      </div>

      {/* Report Selection Tabs */}
      <div className="flex border-b border-slate-200 dark:border-slate-700">
        {[
          { id: 'finance', label: 'Finance Report', icon: FiTrendingUp },
          { id: 'attendance', label: 'Attendance Report', icon: FiClock },
          { id: 'leave', label: 'Leave Report', icon: FiCalendar }
        ].map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveReport(tab.id)}
              className={`flex items-center gap-2 px-6 py-3 text-sm font-medium border-b-2 transition-all -mb-px
                ${activeReport === tab.id 
                  ? 'border-blue-600 text-blue-600 dark:border-blue-400 dark:text-blue-400' 
                  : 'border-transparent text-slate-500 hover:text-slate-700 dark:hover:text-slate-350'}`}
            >
              <Icon className="w-4 h-4" />
              {tab.label}
            </button>
          );
        })}
      </div>

      {activeReport === 'finance' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card title="Monthly Net Earnings" className="lg:col-span-2">
            <div className="h-64 flex flex-col justify-between">
              <div className="flex justify-between text-xs text-slate-400 font-medium">
                <span>Oct 01</span>
                <span>Oct 08</span>
                <span>Oct 15</span>
                <span>Oct 22</span>
                <span>Oct 29</span>
              </div>
              <div className="flex items-end gap-2 h-44 px-2">
                {[40, 55, 30, 85, 95].map((h, i) => (
                  <div key={i} className="flex-1 bg-gradient-to-t from-blue-500 to-indigo-500 dark:from-blue-600 dark:to-indigo-600 rounded-t-md hover:opacity-85 transition-opacity" style={{ height: `${h}%` }}></div>
                ))}
              </div>
              <div className="text-center text-sm font-medium text-slate-600 dark:text-slate-400">Total Net Income this Month: <span className="text-slate-900 dark:text-white font-extrabold">$16,150.00</span></div>
            </div>
          </Card>
          
          <Card title="Expense Breakdown">
            <div className="space-y-4">
              {[
                { name: 'Infrastructure (Hosting/SaaS)', val: '$1,200.00', pct: '70%', color: 'bg-indigo-500' },
                { name: 'Office Supplies', val: '$150.00', pct: '10%', color: 'bg-blue-500' },
                { name: 'Miscellaneous', val: '$350.00', pct: '20%', color: 'bg-emerald-500' }
              ].map((exp, i) => (
                <div key={i} className="space-y-1">
                  <div className="flex justify-between text-xs font-semibold">
                    <span className="text-slate-600 dark:text-slate-400">{exp.name}</span>
                    <span className="text-slate-900 dark:text-white">{exp.val}</span>
                  </div>
                  <div className="w-full bg-slate-100 dark:bg-slate-700 h-2 rounded-full overflow-hidden">
                    <div className={`h-full ${exp.color}`} style={{ width: exp.pct }}></div>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}

      {activeReport === 'attendance' && (
        <Card title="Monthly Attendance Overview">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center py-6">
            <div className="space-y-1">
              <h4 className="text-3xl font-black text-green-600">92.4%</h4>
              <p className="text-sm font-medium text-slate-500">Average Daily Attendance</p>
            </div>
            <div className="space-y-1 border-y md:border-y-0 md:border-x border-slate-200 dark:border-slate-700 py-4 md:py-0">
              <h4 className="text-3xl font-black text-amber-500">1.8h</h4>
              <p className="text-sm font-medium text-slate-500">Average Late Clock-ins</p>
            </div>
            <div className="space-y-1">
              <h4 className="text-3xl font-black text-blue-600">8.2h</h4>
              <p className="text-sm font-medium text-slate-500">Average Work Hours / Day</p>
            </div>
          </div>
        </Card>
      )}

      {activeReport === 'leave' && (
        <Card title="Leave Types Taken (This Year)">
          <div className="space-y-4 max-w-lg mx-auto py-4">
            {[
              { type: 'Sick Leaves', count: 14, color: 'bg-red-500' },
              { type: 'Casual Leaves', count: 28, color: 'bg-blue-500' },
              { type: 'Maternity/Paternity', count: 0, color: 'bg-slate-300' },
              { type: 'Unpaid Leaves', count: 4, color: 'bg-amber-500' }
            ].map((row, i) => (
              <div key={i} className="flex items-center gap-4">
                <span className="text-sm font-semibold w-28 text-slate-650">{row.type}</span>
                <div className="flex-1 bg-slate-100 dark:bg-slate-700 h-4 rounded-full overflow-hidden">
                  <div className={`h-full ${row.color} rounded-full`} style={{ width: `${(row.count / 46) * 100}%` }}></div>
                </div>
                <span className="text-sm font-bold font-mono w-10 text-right">{row.count}</span>
              </div>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
};

export default Reports;
